### ISSUE TITLE
Dataset conventions

### ISSUE THREAD

**Issue by rtkg** [droid-dataset/droid#9]
Hi, 

Thanks for your efforts in making this data available. I do have a couple of questions regarding the used conventions (I'm referring to the dataset schema [here](https://droid-dataset.github.io/droid/the-droid-dataset.html#-dataset-schema):

- what are the entries of a 6d `cartesian_position`, are orientations given as euler angles or in exponential coordinates?
- in which frame is a `cartesian_velocity` expressed (end-effector or base)?
- how are the rotational velocities in a `cartesian_velocity` expressed (euler angle derivatives or angular velocity vector)?
- why is there an `action` entry (joint vel + gripper pos) and an `action_dict` with the same and more information - this seems redundant?

Thanks in advance,
/Robert

**Comment by kpertsch** [comment]
Hi,
Thanks for the questions!

- orientations are Euler angles
- cartesian velocity is in robot base frame
- rotational velocities are delta Euler angles I believe
- per convention the RLDS dataset needs to have an `action` entry, so we've set some "default" there, but since folks may have different preferences for action representation we provide the full info in the `action_dict`, so you can overwrite `action` for your own training runs if you'd like

**Comment by rtkg** [comment]
That clarifies things, thanks for the quick reply. Maybe it would be worth to add this info in the dataset schema comments to avoid further questions along the same line.

**Comment by ruoshiliu** [comment]
Hi @kpertsch ,

Thanks a lot for releasing the code!

What's the convention used for the Euler angles for "cartesian_position" in observation and action? E.g. xyz, xzy, zyx etc.

Thank you!

**Comment by AlexanderKhazatsky** [comment]
Hello, the convection is xyz :)
